# Generated by Django 3.2.4 on 2021-06-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_planed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompleted',
            new_name='date_completed',
        ),
    ]
