# Generated by Django 3.2.4 on 2021-07-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_datecompleted_todo_date_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-planed_date']},
        ),
    ]
